ERROR: 2020/03/31 18:45:55 customlog_test.go:48: Something has failed
